server.port: ${port:8081}
kafka-global-consumer:
  # The value comes from the Embedded Kafka: ${spring.embedded.kafka.brokers}
  bootstrap-servers: localhost:9092

#This configuration is specific for Person domain only.
person-auto-commit-consumer:
  auto-offset-reset: earliest
  request-timeout: 60000
  session-timeout: 30000
  # Retry Attempt must be > 0
  # If the retry-attempt > 1, the error handler will be only executed after all retry attempt.
  # But we also want to test the error handler, so I set retry-attempt is 1.
  retry-attempt: 1
  retry-backoff-period: 3000

person-manual-commit-consumer:
  auto-commit: false
  auto-commit-interval: 3000
  ack-on-error: false
  ack-mode: MANUAL
  session-timeout: 25000
  retry-attempt: 1
  retry-backoff-period: 10000

app:
  topic:
    example: topic.01
